services:
  app:
    build: .
    image: ${DOCKERHUB_USERNAME}/fintracker-api:latest
    labels:
      - "traefik.enable=true"

      # PUBLIC DOMAIN
      - "traefik.http.routers.fin-public.rule=Host(`api.suissetiawan.my.id`) && PathPrefix(`/fintracker`)"
      - "traefik.http.routers.fin-public.entrypoints=web"

      # LOCAL DOMAIN
      - "traefik.http.routers.fin-local.rule=Host(`api.suissetiawan.home`) && PathPrefix(`/fintracker`)"
      - "traefik.http.routers.fin-local.entrypoints=web"

      # SERVICE PORT
      - "traefik.http.services.fin.loadbalancer.server.port=8080"

    container_name: api-fintracker
    ports:
      - "8082:8080"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - financial-tracker-network

networks:
  financial-tracker-network:
    name: financial-tracker-network
