services:
  app:
    build: .
    image: ${DOCKERHUB_USERNAME}/fintracker-api:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.fintracker.loadbalancer.server.port=8080"

      - "traefik.http.routers.fintracker-public.rule=Host(`api.suissetiawan.my.id`) && PathPrefix(`/fintracker`)"
      - "traefik.http.routers.fintracker-public.entrypoints=web"
      - "traefik.http.routers.fintracker-local.rule=Host(`api.suissetiawan.home`) && PathPrefix(`/fintracker`)"
      - "traefik.http.routers.fintracker-local.entrypoints=web"

    container_name: api-fintracker
    ports:
      - "8082:8080"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - financial-tracker-network

networks:
  financial-tracker-network:
    name: financial-tracker-network
