services:
  app:
    build: .
    image: ${DOCKERHUB_USERNAME}/fintracker-api:latest
    container_name: fintracker-api
    ports:
      - "8082:8080"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - financial-tracker-network

networks:
  financial-tracker-network:
    name: financial-tracker-network
