# DataSource
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA Configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Redis Configuration
spring.data.redis.repositories.enabled=false

# JWT Configuration
jwt.secret=de9a0f54130e7f095570c44968b2877def66cdd0cffd85f92450bb1f90e6eacb
jwt.refresh.secret=5c2f8d1a4b3c2d1e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e
# Expiration time in seconds
jwt.expiration=30
jwt.refresh.expiration=300