spring.application.name=financial-tracker

# JPA common config
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# JWT expiration (seconds)
jwt.expiration=3600
jwt.refresh.expiration=86400


# Swagger Configuration
springdoc.swagger-ui.path=/v1/swagger-ui.html
springdoc.api-docs.path=/v1/api-docs
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.operations-sorter=none
springdoc.default-flat-param-object=true
springdoc.swagger-ui.persistAuthorization=true