# DataSource
spring.datasource.url=jdbc:mysql://192.168.0.14:3306/financial_tracker?createdbIfNotExists=true
spring.datasource.username=casaos
spring.datasource.password=casaos

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis Configuration
spring.data.redis.host=192.168.0.14
spring.data.redis.port=6379

# JWT Configuration
jwt.secret=aa03b74d36525cff237d8ef7348d6802362893618e315960209375e525f16b00
jwt.refresh.secret=b1f4e4d5c3e8f7a9b2c6d4e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7g8
# Expiration time in seconds
jwt.expiration=7200
jwt.refresh.expiration=172800